/**
 * Voltix seed data — demo users + smartphone catalog.
 * Run: npm run seed   (from /server)
 */
require('dotenv').config();
const connectDB = require('./config/db');
const User = require('./models/User');
const Product = require('./models/Product');
const Cart = require('./models/Cart');
const Order = require('./models/Order');
const Review = require('./models/Review');

/* Tiny valid one-page PDF used as the demo business license (no binary assets needed) */
function demoLicensePdf(shopName) {
  const text = `Voltix Business License - ${shopName}`
    .replace(/[()\\]/g, '')
    .slice(0, 80);
  const stream =
    'BT /F1 18 Tf 60 740 Td (' + text + ') Tj ET\n' +
    'BT /F1 11 Tf 60 700 Td (Demo document generated by the Voltix seed script.) Tj ET\n' +
    'BT /F1 11 Tf 60 680 Td (Status: VERIFIED-DEMO. Issued for marketplace demonstration.) Tj ET\n';
  const objects = [];
  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objects[2] = '<< /Type /Pages /Kids [3 0 R] /Count 1 >>';
  objects[3] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>';
  objects[4] = `<< /Length ${stream.length} >>\nstream\n${stream}endstream`;
  objects[5] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (let i = 1; i < objects.length; i++) {
    offsets[i] = pdf.length;
    pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xrefPos = pdf.length;
  pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let i = 1; i < objects.length; i++) {
    pdf += String(offsets[i]).padStart(10, '0') + ' 00000 n \n';
  }
  pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;
  return Buffer.from(pdf, 'latin1');
}

/* Real product photography — hotlinkable Unsplash CDN URLs (all verified 200 image/jpeg) */
const IMG = (id, w = 800) => `https://images.unsplash.com/${id}?w=${w}&q=80&auto=format&fit=crop`;

/* 3D models. smartphone.glb is generated locally (node client/tests/make-smartphone-glb.mjs)
   and served same-origin from client/public/models/ — named parts (Phone_Body/Phone_Back/
   Phone_Frame colorable, Screen/Camera_* protected) so variant swatches tint it correctly.
   The network URLs below are verified CORS-enabled variety models if a listing ever
   needs a showcase object instead. */
const GLB = {
  smartphone: '/models/smartphone.glb',
  helmet: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb',
  toyCar: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/ToyCar/glTF-Binary/ToyCar.glb',
  duck: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/Duck/glTF-Binary/Duck.glb',
  astronaut: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
};

/* Hotspots authored per 3D model. The viewer normalizes every GLB so its largest
   dimension = 7 units, centered at origin — coordinates below live in that space.
   `phone` matches the procedural phone in client/src/three/PhoneModel.jsx. */
const HOTSPOTS = {
  phone: (name) => [
    {
      title: '6.9\u2033 ' + name + ' AMOLED',
      description: '144Hz LTPO display with 2600-nit peak brightness and ultra-thin bezels.',
      position: { x: 0, y: 0.6, z: 0.32 },
    },
    {
      title: '108MP Triple Camera',
      description: 'Main sensor with OIS, 12MP ultrawide and 10MP 5x periscope telephoto.',
      position: { x: -0.95, y: 2.5, z: -0.48 },
    },
    {
      title: 'Under-display Fingerprint',
      description: 'Ultrasonic fingerprint sensor unlocks in 0.18s.',
      position: { x: 1.78, y: 1.05, z: 0 },
    },
    {
      title: '90W Turbo Charging',
      description: 'USB-C with 90W wired charging \u2014 50% in 12 minutes.',
      position: { x: 0, y: -3.35, z: 0.24 },
    },
  ],
  helmet: [
    {
      title: 'Scratched Visor',
      description: 'Battle-worn visor with iridescent wear marks — scan it to toggle HUD modes.',
      position: { x: 0, y: 0.5, z: 3.3 },
    },
    {
      title: 'Matte Composite Shell',
      description: 'Impact-diffusing composite armor rated for debris fields up to 12 km/s.',
      position: { x: -3.2, y: 0.2, z: 0.6 },
    },
    {
      title: 'Top Vent Array',
      description: 'Micro-perforated heat exchangers keep the suit at 21\u00b0C on EVA.',
      position: { x: 0, y: 3.1, z: 0.4 },
    },
    {
      title: 'Comm Neck Ring',
      description: 'Rotating collar with adaptive noise-cancelling comms and O\u2082 coupling.',
      position: { x: 0.9, y: -3.1, z: 1.4 },
    },
  ],
  toyCar: [
    {
      title: 'Polished Body Panels',
      description: 'Hand-polished steel panels with 9 coats of lacquer — showroom ready.',
      position: { x: 0, y: 0.5, z: 1.5 },
    },
    {
      title: 'Alloy Wheels',
      description: 'Forged 5-spoke alloys with performance rubber and red calipers.',
      position: { x: 2.1, y: -1.5, z: 0.4 },
    },
    {
      title: 'Panoramic Cabin Glass',
      description: 'UV-filtering curved glass with a whisper-quiet seal.',
      position: { x: -0.4, y: 1.5, z: 0 },
    },
    {
      title: 'Signature Headlamps',
      description: 'Adaptive LED matrix lamps with animated welcome sequence.',
      position: { x: 2.7, y: -0.3, z: 1.1 },
    },
  ],
  duck: [
    {
      title: 'Classic Rubber Head',
      description: 'Squeeze-activated squeaker — certified fun for all ages.',
      position: { x: 1.6, y: 1.3, z: 0 },
    },
    {
      title: 'Buoyant Hull Body',
      description: 'Sealed hollow body keeps it afloat even with 2 kg of cargo aboard.',
      position: { x: 0, y: -0.5, z: 1.3 },
    },
    {
      title: 'Aerodynamic Tail',
      description: 'Sculpted tail feathers reduce bath-time drag by up to 12%.',
      position: { x: -2.5, y: 0.5, z: 0 },
    },
  ],
  astronaut: [
    {
      title: 'EVA Helmet',
      description: 'Gold-coated visor filters 99.98% of UV and IR radiation.',
      position: { x: 0, y: 2.5, z: 0.6 },
    },
    {
      title: 'Life-Support Backpack',
      description: '8-hour Primary Life Support System with CO\u2082 scrubbers.',
      position: { x: 0, y: 0.4, z: -1.3 },
    },
    {
      title: 'Pressurized Boots',
      description: 'Grip-optimized soles rated for lunar regolith and station handrails.',
      position: { x: 0.4, y: -3.1, z: 0 },
    },
  ],
};

async function seed() {
  await connectDB();

  console.log('🧹 Clearing existing data…');
  await Promise.all([
    User.deleteMany({}),
    Product.deleteMany({}),
    Cart.deleteMany({}),
    Order.deleteMany({}),
    Review.deleteMany({}),
  ]);

  console.log('👤 Creating users…');
  const [, sellerApproved, sellerPending] = await Promise.all([
    User.create({ name: 'Voltix Admin', email: 'admin@voltix.com', password: 'admin123', role: 'admin', status: 'active', isVerified: true }),
    User.create({ name: 'Nova Gadgets', email: 'seller@voltix.com', password: 'seller123', role: 'seller', shopName: 'Nova Gadgets', status: 'approved', isVerified: true }),
    User.create({ name: 'Orbit Mobiles', email: 'pending@voltix.com', password: 'seller123', role: 'seller', shopName: 'Orbit Mobiles', status: 'pending', isVerified: true }),
    User.create({ name: 'Demo Customer', email: 'customer@voltix.com', password: 'cust123', role: 'customer', status: 'active', isVerified: true }),
  ]);

  /* attach demo business licenses so the admin approval queue is testable */
  const fs = require('fs');
  const path = require('path');
  const uploadDir = path.join(__dirname, '..', 'uploads');
  fs.mkdirSync(uploadDir, { recursive: true });
  for (const [user, label] of [[sellerApproved, 'nova-gadgets'], [sellerPending, 'orbit-mobiles']]) {
    const file = `license-${label}-${user._id}.pdf`;
    fs.writeFileSync(path.join(uploadDir, file), demoLicensePdf(user.shopName));
    user.licenseUrl = `/uploads/${file}`;
    user.licenseOriginalName = `${label}-business-license.pdf`;
    await user.save();
  }
  console.log('📄 Demo business licenses attached to both sellers');

  console.log('📱 Creating products…');
  const mk = (p) => p; // products now carry their own network image + model URLs

  const products = await Product.insertMany([
    mk({
      seller: sellerApproved._id, name: 'Nova X1 Pro', brand: 'NovaTech', category: 'smartphone',
      description: 'Flagship powerhouse with a titanium frame. The Nova X1 Pro pairs a 3nm octa-core chip with a stunning 6.9\u2033 LTPO AMOLED display, a 108MP triple camera and 90W turbo charging.',
      price: 1099, compareAtPrice: 1299, stock: 24, accent: '#2563eb',
      images: [IMG('photo-1511707171634-5f897ff02aa9'), IMG('photo-1592750475338-74b7b21085ab')],
      model3dUrl: GLB.smartphone,
      specs: [
        { key: 'Display', value: '6.9\u2033 LTPO AMOLED, 144Hz, 2600 nits' },
        { key: 'Chipset', value: 'Vertex V3 (3nm), up to 3.4GHz' },
        { key: 'Memory', value: '12GB RAM' },
        { key: 'Storage', value: '256GB / 512GB UFS 4.0' },
        { key: 'Camera', value: '108MP + 12MP UW + 10MP 5x Tele' },
        { key: 'Battery', value: '5400mAh, 90W wired / 15W wireless' },
        { key: 'OS', value: 'Android 15' },
      ],
      hotspots: HOTSPOTS.phone('Dynamic'), status: 'approved', featured: true,
      variants: [
        { name: 'Color', values: [
          { value: 'Ocean Blue', priceDelta: 0, swatch: '#1e3f8f' },
          { value: 'Graphite', priceDelta: 0, swatch: '#2c2e33' },
          { value: 'Silver', priceDelta: 20, swatch: '#d8dade' },
        ] },
        { name: 'Storage', values: [
          { value: '256GB', priceDelta: 0, stock: 5 },
          { value: '512GB', priceDelta: 150, stock: 12 },
        ] },
      ],
    }),
    mk({
      seller: sellerApproved._id, name: 'Pulse S24 Ultra', brand: 'Pulse', category: 'smartphone',
      description: 'Built for creators: vapor-chamber cooled gaming chipset, quad stereo speakers and an included stylus that slots into the body.',
      price: 899, compareAtPrice: null, stock: 41, accent: '#8b5cf6',
      images: [IMG('photo-1567581935884-3349723552ca'), IMG('photo-1598327105666-5b89351aff97')],
      model3dUrl: GLB.smartphone,
      specs: [
        { key: 'Display', value: '6.7\u2033 OLED, 120Hz' },
        { key: 'Chipset', value: 'Fusion G2 with vapor chamber cooling' },
        { key: 'Memory', value: '8GB / 12GB RAM' },
        { key: 'Camera', value: '64MP + 8MP UW + 5MP Macro' },
        { key: 'Battery', value: '5000mAh, 67W charging' },
        { key: 'Extras', value: 'Stylus included, IP68' },
      ],
      variants: [
        { name: 'Color', values: [
          { value: 'Lavender', priceDelta: 0, swatch: '#a08fd8' },
          { value: 'Midnight Black', priceDelta: 0, swatch: '#16171c' },
        ] },
        { name: 'Memory', values: [
          { value: '8GB', priceDelta: 0 },
          { value: '12GB', priceDelta: 100 },
        ] },
      ],
      hotspots: HOTSPOTS.phone('Super'), status: 'approved', featured: true,
    }),
    mk({
      seller: sellerApproved._id, name: 'Aurora A54 5G', brand: 'Aurora', category: 'smartphone',
      description: 'The everyday champion \u2014 clean software, a bright 6.5\u2033 screen and two-day battery life at a friendly price.',
      price: 329, compareAtPrice: 379, stock: 87, accent: '#10b981',
      images: [IMG('photo-1512941937669-90a1b58e7e9c'), IMG('photo-1601784551446-20c9e07cdbdb')],
      model3dUrl: GLB.smartphone, // local phone GLB — swatch tints Phone_Body/Back/Frame
      specs: [
        { key: 'Display', value: '6.5\u2033 IPS LCD, 90Hz' },
        { key: 'Chipset', value: 'Helio G99' },
        { key: 'Memory', value: '6GB RAM' },
        { key: 'Battery', value: '6000mAh, 33W charging' },
      ],
      variants: [{ name: 'Color', values: [
        { value: 'Mint Green', priceDelta: 0, swatch: '#79c7ac' },
        { value: 'Graphite', priceDelta: 0, swatch: '#2c2e33' },
      ] }],
      hotspots: HOTSPOTS.phone('HD+'), status: 'approved', featured: false,
    }),
    mk({
      seller: sellerApproved._id, name: 'Kite K7 Lite', brand: 'Kite', category: 'smartphone',
      description: 'Featherweight design, heavyweight endurance. Just 7.1mm thin with a 5200mAh battery.',
      price: 249, compareAtPrice: null, stock: 60, accent: '#ec4899',
      images: [IMG('photo-1591337676887-a217a6970a8a'), IMG('photo-1533228100845-08145b01de14')],
      model3dUrl: GLB.smartphone,
      specs: [
        { key: 'Display', value: '6.4\u2033 AMOLED, 120Hz' },
        { key: 'Thickness', value: '7.1mm, 168g' },
        { key: 'Battery', value: '5200mAh' },
      ],
      variants: [{ name: 'Color', values: [
        { value: 'Rose Pink', priceDelta: 0, swatch: '#ec4899' },
        { value: 'White', priceDelta: 0, swatch: '#eceae4' },
      ] }],
      hotspots: HOTSPOTS.phone('AMOLED'), status: 'approved', featured: false,
    }),
    mk({
      seller: sellerApproved._id, name: 'Zenith Fold Neo', brand: 'Zenith', category: 'smartphone',
      description: 'A book-style foldable that opens into a 7.6\u2033 tablet. Multitask like never before.',
      price: 1499, compareAtPrice: null, stock: 9, accent: '#f59e0b',
      images: [IMG('photo-1605236453806-6ff36851218e'), IMG('photo-1541873676-a18131494184')],
      model3dUrl: GLB.smartphone,
      specs: [
        { key: 'Inner Display', value: '7.6\u2033 foldable AMOLED 120Hz' },
        { key: 'Cover Display', value: '6.2\u2033 AMOLED' },
        { key: 'Hinge', value: 'Flex hinge, free-stop' },
      ],
      variants: [{ name: 'Color', values: [
        { value: 'Gold', priceDelta: 50, swatch: '#d8b26e' },
        { value: 'Black', priceDelta: 0, swatch: '#16171c' },
      ] }],
      hotspots: HOTSPOTS.phone('FlexView'), status: 'approved', featured: true,
    }),
    mk({
      seller: sellerApproved._id, name: 'Orbit O12', brand: 'Orbit', category: 'smartphone',
      description: 'Listing awaiting admin approval \u2014 this is how a submitted product looks to reviewers.',
      price: 459, compareAtPrice: null, stock: 30, accent: '#06b6d4',
      images: [IMG('photo-1605170439002-90845e8c0137'), IMG('photo-1607936854279-55e8a4c64888')],
      model3dUrl: GLB.smartphone,
      specs: [{ key: 'Display', value: '6.6\u2033 OLED 120Hz' }],
      variants: [{ name: 'Color', values: [{ value: 'Cyan', priceDelta: 0, swatch: '#06b6d4' }] }],
      hotspots: [], status: 'pending', featured: false,
    }),
    mk({
      seller: sellerApproved._id, name: 'Nova X1 Draft', brand: 'NovaTech', category: 'smartphone',
      description: 'A private draft only the seller can see until it is submitted for approval.',
      price: 999, compareAtPrice: null, stock: 0, accent: '#64748b',
      images: [IMG('photo-1580910051074-3eb694886505'), IMG('photo-1585060544812-6b45742d762f')],
      model3dUrl: GLB.smartphone,
      specs: [], variants: [], hotspots: [], status: 'draft', featured: false,
    }),
  ]);
  console.log(`   inserted ${products.length} products`);

  /* ---------- demo orders + reviews ---------- */
  console.log('🧾 Creating a delivered demo order…');
  const customer = await User.findOne({ email: 'customer@voltix.com' });
  const nova = products.find((p) => p.name === 'Nova X1 Pro');
  const aurora = products.find((p) => p.name === 'Aurora A54 5G');

  const demoOrder = await Order.create({
    user: customer._id,
    items: [
      { product: nova._id, name: nova.name, image: nova.images[0], unitPrice: nova.price, qty: 1,
        variant: [{ name: 'Color', value: 'Ocean Blue' }, { name: 'Storage', value: '256GB' }] },
      { product: aurora._id, name: aurora.name, image: aurora.images[0], unitPrice: aurora.price, qty: 2,
        variant: [{ name: 'Color', value: 'Mint Green' }] },
    ],
    subtotal: nova.price + aurora.price * 2,
    shippingFee: 0,
    total: nova.price + aurora.price * 2,
    paymentMethod: 'cod',
    shippingAddress: { fullName: 'Demo Customer', phone: '555-0100', line1: '1 Main St', city: 'Addis Ababa', country: 'Ethiopia' },
    status: 'delivered',
  });

  console.log('⭐ Creating demo reviews…');
  const reviews = await Review.insertMany([
    {
      product: nova._id, user: customer._id, orderItem: `${demoOrder._id}:0`, rating: 5,
      comment: 'The 3D view sold me — I could see the camera bump and ports up close before ordering. Delivery was quick and the phone is flawless.',
    },
    {
      product: aurora._id, user: customer._id, orderItem: `${demoOrder._id}:1`, rating: 4,
      comment: 'Great battery, clean software. Wish it had a brighter screen outdoors, but unbeatable at this price.',
    },
  ]);

  // keep product aggregates in sync
  for (const r of reviews) {
    const [stats] = await Review.aggregate([
      { $match: { product: r.product } },
      { $group: { _id: '$product', num: { $sum: 1 }, avg: { $avg: '$rating' } } },
    ]);
    await Product.findByIdAndUpdate(r.product, {
      numReviews: stats?.num || 0,
      averageRating: stats ? Math.round(stats.avg * 10) / 10 : 0,
    });
  }
  console.log(`   inserted ${reviews.length} reviews + updated rating aggregates`);

  console.log('\n✅ Seed complete!\n');
  console.log('Demo accounts:');
  console.log('  Admin    → admin@voltix.com    / admin123   (approve sellers & products)');
  console.log('  Seller   → seller@voltix.com   / seller123  (approved, owns the catalog)');
  console.log('  Seller   → pending@voltix.com  / seller123  (cannot log in until approved)');
  console.log('  Customer → customer@voltix.com / cust123   (has a delivered order + reviews)');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
